-- Primero crear la tabla cat_builder.
create table cat_builder(
    cat_id number generated by default as identity,
    cat varchar2(1000) not null, 
    subcat varchar2(1000) not null,

    primary key(cat_id)
);

select * from cat_builder;

-- Segundo importar el archivo de texto con los datos utilizando sqldeveloper.

-- Tercero insertar los datos a la tabla categoria.
insert into categoria(nombre, descripcion, is_deleted)
select
distinct cat,
'-',
0
from cat_builder
order by cat;

select * from categoria;

-- Cuarto insertar todos los datos a la tabla subcategoria.
insert into subcategoria(categoria_fk, nombre, descripcion, is_deleted)
select 
ca.categoria_id,
cb.subcat,
'-',
0
from cat_builder cb
inner join categoria ca on ca.nombre = cb.cat;

select * from subcategoria;