-- Script de creacion de base de datos
-- Primer proyecto programado - BDII

create table email(
    email_id number generated by default as identity,
    email_address varchar2(254) not null, 
    is_deleted number(1) not null,

    primary key(email_id)
);

create table tipo_identificacion(
    tipo_identificacion_id number generated by default as identity,
    nombre varchar2(40) not null,
    is_deleted number(1) not null,

    primary key(tipo_identificacion_id)
);

create table identificacion(
    identificacion_id number generated by default as identity,
    tipo_ident_fk number not null,
    descripcion varchar2(50) not null, 
    --^El numero de cedula va aqui, no se me ocurre otra manera no ambigua de nombrar este campo.
    is_deleted number(1) not null,

    primary key(identificacion_id),

    constraint fk_constr_tipoID_identificacion
    -- Foreign key: tipo_identificacion <-> identificacion
    foreign key(tipo_ident_fk) 
    references tipo_identificacion(tipo_identificacion_id)
    on delete cascade
);

create table persona(
    persona_id number generated by default as identity,
    identificacion_fk number not null,
    email_fk number not null,
    nombre varchar2(40) not null,
    apellido varchar2(40) not null,
    is_deleted number(1) not null,

    primary key(persona_id),

    constraint fk_constr_persona_email
    -- Foreign key: persona <-> email
    foreign key(email_fk)
    references email(email_id)
    on delete cascade,

    constraint fk_constr_persona_identificacion
    -- Foreign key: persona <-> identificacion
    foreign key(identificacion_fk)
    references identificacion(identificacion_id)
    on delete cascade
);

create table direccion(
    direccion_id number generated by default as identity,
    persona_fk number not null,
    descripcion varchar2(100) not null,
    distrito varchar2(100) not null,
    canton varchar2(100) not null,
    provincia varchar2(100) not null,
    pais varchar2(100) not null,
    is_deleted number(1) not null,

    primary key(direccion_id),

    constraint fk_constr_direccion_persona
    -- Foreign key: direccion <-> persona
    foreign key(persona_fk)
    references persona(persona_id)
    on delete cascade
);

create table telefono(
    telefono_id number generated by default as identity,
    persona_fk number not null,
    num_telefono varchar2(30) not null,
    descripcion varchar2(50) not null,
    is_deleted number(1) not null, 

    primary key(telefono_id),
    constraint fk_constr_telefono_persona
    -- Foreign key: telefono <-> persona
    foreign key(persona_fk)
    references persona(persona_id)
    on delete cascade
);

create table usuario(
    usuario_id number generated by default as identity,
    persona_fk number not null,
    username varchar2(50) not null,
    passwd varchar2(100) not null,
    dkey varchar2(32) not null, --llave para desencriptar la contrasena.
    is_deleted number(1) not null,

    primary key(usuario_id),

    constraint fk_constr_usuario_persona
    -- Foreign key: usuario <-> persona
    foreign key(persona_fk)
    references persona(persona_id)
    on delete cascade
);

create table administrador(
    administrador_id number generated by default as identity,
    usuario_fk number not null,
    is_deleted number(1) not null,

    primary key(administrador_id),
    constraint fk_constr_administrador_usuario
    -- Foreign key: administrador <-> usuario 
    foreign key(usuario_fk)
    references usuario(usuario_id)
    on delete cascade
);

create table comentario(
    comentario_id number generated by default as identity,
    usuario_fk number not null,
    comentario varchar2(500) not null,
    rating float(4) not null,
    is_deleted number(1) not null,

    primary key(comentario_id),
    constraint fk_constr_comentario_usuario
    -- Foreign key: comentario <-> usuario
    foreign key(usuario_fk)
    references usuario(usuario_id)
    on delete cascade
);

create table categoria(
    categoria_id number generated by default as identity,
    nombre varchar2(200) not null,
    descripcion varchar2(300) not null, 
    is_deleted number(1) not null,

    primary key(categoria_id)
);

create table subcategoria(
    subcategoria_id number generated by default as identity, 
    categoria_fk number not null,
    nombre varchar2(200) not null,
    descripcion varchar2(300) not null,
    is_deleted number(1) not null,

    primary key(subcategoria_id),
    constraint fk_constr_subcat_categoria
    -- Foreign key: subcategoria <-> categoria
    foreign key(categoria_fk)
    references categoria(categoria_id)
    on delete cascade
);

create table item(
    item_id number generated by default as identity,
    usuario_fk number not null,
    categoria_fk number not null,
    subcategoria_fk number not null,
    nombre varchar2(50) not null,
    descripcion varchar2(300) not null,
    is_deleted number(1) not null,

    primary key(item_id),
    constraint fk_constr_item_usuario
    -- Foreign key: item <-> usuario
    foreign key(usuario_fk)
    references usuario(usuario_id)
    on delete cascade,

    constraint fk_constr_item_categoria
    -- Foreign key: item <-> categoria
    foreign key(categoria_fk)
    references categoria(categoria_id)
    on delete cascade,

    constraint fk_constr_item_subcategoria
    -- Foreign key: item <-> subcategoria
    foreign key(subcategoria_fk)
    references subcategoria(subcategoria_id)
    on delete cascade
);

create table valores(
    valores_id number generated by default as identity,
    porcentaje_mejora float(4) not null,
    incremento_minimo number(10,4) not null,
    -- ^ Incremento minimo es un valor monetario
    is_deleted number(1) not null,

    primary key(valores_id)
);

create table subasta(
    subasta_id number generated by default as identity,
    item_fk number not null,
    comentario_vendedor_fk number not null,
    comentario_comprador_fk number not null,
    usuario_vendedor_fk number not null,
    valores_fk number not null,
    nombre varchar2(100) not null,
    descripcion varchar2(400) not null,
    fecha_inicio timestamp(2) not null,
    fecha_fin timestamp(2) not null,
    valor_inicial number(10,4) not null,
    valor_actual number(10,4) not null,
    detalles_de_envio varchar(500) not null,
    es_activa number(1) not null,
    is_deleted number(1) not null,

    primary key(subasta_id),

    constraint fk_subasta_item
    -- Foreign key: subasta <-> item
    foreign key(item_fk)
    references item(item_id)
    on delete cascade,

    constraint fk_subasta_comentario_vendedor
    -- Foreign key: subasta <-> comentario
    foreign key(comentario_vendedor_fk)
    references comentario(comentario_id)
    on delete cascade,

    constraint fk_subasta_comentario_comprador
    -- Foreign key: subasta <-> comentario
    foreign key(comentario_comprador_fk)
    references comentario(comentario_id)
    on delete cascade,

    constraint fk_subasta_valores
    -- Foreign key: subasta <-> valores 
    foreign key (valores_fk)
    references valores(valores_id)
    on delete cascade
);

create table puja(
    puja_id number generated by default as identity,
    subasta_fk number not null,
    usuario_comprador_fk number not null,
    monto number(10,4),
    fecha_y_tiempo timestamp(2),
    es_ganador number(1),
    es_exitosa number(1),
    is_deleted number(1),

    primary key(puja_id),

    constraint fk_constr_puja_subasta
    -- Foreign key: puja <-> subasta 
    foreign key(subasta_fk)
    references subasta(subasta_id)
    on delete cascade,

    constraint fk_constr_puja_usuario_comprador
    foreign key(usuario_comprador_fk)
    references usuario(usuario_id)
    on delete cascade
);