DECLARE
  IN_SUBASTA_NOMBRE VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_MONTO NUMBER;
BEGIN
  IN_SUBASTA_NOMBRE := 'picassoooooooo';
  IN_USERNAME := 'jpfeng';
  IN_MONTO := 15234.420;

  SP_NUEVA_PUJA(
    IN_SUBASTA_NOMBRE => IN_SUBASTA_NOMBRE,
    IN_USERNAME => IN_USERNAME,
    IN_MONTO => IN_MONTO
  );
--rollback; 
END;
