DECLARE
  IN_NOMBRE_ITEM VARCHAR2(200);
  IN_NOMBRE_USUARIO VARCHAR2(200);
  IN_NOMBRE_SUBASTA VARCHAR2(200);
  IN_DESC_SUBASTA VARCHAR2(200);
  IN_CANT_DIAS NUMBER;
  IN_VALOR_INICIAL NUMBER;
  IN_DETALLES_ENVIO VARCHAR2(200);
BEGIN
  IN_NOMBRE_ITEM := 'Picasso xD';
  IN_NOMBRE_USUARIO := 'mctula';
  IN_NOMBRE_SUBASTA := 'picassoooooooo';
  IN_DESC_SUBASTA := 'subasto esta vara';
  IN_CANT_DIAS := 10;
  IN_VALOR_INICIAL := 4000;
  IN_DETALLES_ENVIO := 'Venga por la vara';

  SP_NUEVA_SUBASTA(
    IN_NOMBRE_ITEM => IN_NOMBRE_ITEM,
    IN_NOMBRE_USUARIO => IN_NOMBRE_USUARIO,
    IN_NOMBRE_SUBASTA => IN_NOMBRE_SUBASTA,
    IN_DESC_SUBASTA => IN_DESC_SUBASTA,
    IN_CANT_DIAS => IN_CANT_DIAS,
    IN_VALOR_INICIAL => IN_VALOR_INICIAL,
    IN_DETALLES_ENVIO => IN_DETALLES_ENVIO
  );
--rollback; 
END;
/
DECLARE
  IN_NOMBRE_ITEM VARCHAR2(200);
  IN_NOMBRE_USUARIO VARCHAR2(200);
  IN_NOMBRE_SUBASTA VARCHAR2(200);
  IN_DESC_SUBASTA VARCHAR2(200);
  IN_CANT_DIAS NUMBER;
  IN_VALOR_INICIAL NUMBER;
  IN_DETALLES_ENVIO VARCHAR2(200);
BEGIN
  IN_NOMBRE_ITEM := 'HERNAN JIMENEZ NFT';
  IN_NOMBRE_USUARIO := 'jpfeng';
  IN_NOMBRE_SUBASTA := 'escubiNFT';
  IN_DESC_SUBASTA := 'subasto esta vara';
  IN_CANT_DIAS := 5;
  IN_VALOR_INICIAL := 4000;
  IN_DETALLES_ENVIO := 'Venga por la vara';

  SP_NUEVA_SUBASTA(
    IN_NOMBRE_ITEM => IN_NOMBRE_ITEM,
    IN_NOMBRE_USUARIO => IN_NOMBRE_USUARIO,
    IN_NOMBRE_SUBASTA => IN_NOMBRE_SUBASTA,
    IN_DESC_SUBASTA => IN_DESC_SUBASTA,
    IN_CANT_DIAS => IN_CANT_DIAS,
    IN_VALOR_INICIAL => IN_VALOR_INICIAL,
    IN_DETALLES_ENVIO => IN_DETALLES_ENVIO
  );
--rollback; 
END;
/