-- Script para insertar usuarios a la base de datos.

DECLARE
  IN_NOMBRE VARCHAR2(200);
  IN_APELLIDO VARCHAR2(200);
  IN_IDENTIF VARCHAR2(200);
  IN_TIPO_IDENTIF VARCHAR2(200);
  IN_EMAIL VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_PASSWD VARCHAR2(200);
BEGIN
  IN_NOMBRE := 'Gustavo';
  IN_APELLIDO := 'Torres';
  IN_IDENTIF := '41352135';
  IN_TIPO_IDENTIF := 'Pasaporte';
  IN_EMAIL := 'xd@xd.xd';
  IN_USERNAME := 'fenrirchan';
  IN_PASSWD := 'fenrirchan';

  SP_NUEVO_CLIENTE(
    IN_NOMBRE => IN_NOMBRE,
    IN_APELLIDO => IN_APELLIDO,
    IN_IDENTIF => IN_IDENTIF,
    IN_TIPO_IDENTIF => IN_TIPO_IDENTIF,
    IN_EMAIL => IN_EMAIL,
    IN_USERNAME => IN_USERNAME,
    IN_PASSWD => IN_PASSWD
  );
--rollback; 
END;
/
DECLARE
  IN_NOMBRE VARCHAR2(200);
  IN_APELLIDO VARCHAR2(200);
  IN_IDENTIF VARCHAR2(200);
  IN_TIPO_IDENTIF VARCHAR2(200);
  IN_EMAIL VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_PASSWD VARCHAR2(200);
BEGIN
  IN_NOMBRE := 'Andres';
  IN_APELLIDO := 'Garcia';
  IN_IDENTIF := '10349287';
  IN_TIPO_IDENTIF := 'Cedula Juridica';
  IN_EMAIL := 'mctula@gmail.com';
  IN_USERNAME := 'mctula';
  IN_PASSWD := 'mctula';

  SP_NUEVO_CLIENTE(
    IN_NOMBRE => IN_NOMBRE,
    IN_APELLIDO => IN_APELLIDO,
    IN_IDENTIF => IN_IDENTIF,
    IN_TIPO_IDENTIF => IN_TIPO_IDENTIF,
    IN_EMAIL => IN_EMAIL,
    IN_USERNAME => IN_USERNAME,
    IN_PASSWD => IN_PASSWD
  );
--rollback; 
END;
/
DECLARE
  IN_NOMBRE VARCHAR2(200);
  IN_APELLIDO VARCHAR2(200);
  IN_IDENTIF VARCHAR2(200);
  IN_TIPO_IDENTIF VARCHAR2(200);
  IN_EMAIL VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_PASSWD VARCHAR2(200);
BEGIN
  IN_NOMBRE := 'Jose Pablo';
  IN_APELLIDO := 'Feng';
  IN_IDENTIF := '12937429';
  IN_TIPO_IDENTIF := 'Pasaporte';
  IN_EMAIL := 'jpfeng@gmail.com';
  IN_USERNAME := 'jpfeng';
  IN_PASSWD := 'jpfeng';

  SP_NUEVO_CLIENTE(
    IN_NOMBRE => IN_NOMBRE,
    IN_APELLIDO => IN_APELLIDO,
    IN_IDENTIF => IN_IDENTIF,
    IN_TIPO_IDENTIF => IN_TIPO_IDENTIF,
    IN_EMAIL => IN_EMAIL,
    IN_USERNAME => IN_USERNAME,
    IN_PASSWD => IN_PASSWD
  );
--rollback; 
END;
/
DECLARE
  IN_NOMBRE VARCHAR2(200);
  IN_APELLIDO VARCHAR2(200);
  IN_IDENTIF VARCHAR2(200);
  IN_TIPO_IDENTIF VARCHAR2(200);
  IN_EMAIL VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_PASSWD VARCHAR2(200);
BEGIN
  IN_NOMBRE := 'Andres';
  IN_APELLIDO := 'Cornejo';
  IN_IDENTIF := '12398472325325';
  IN_TIPO_IDENTIF := 'Cedula';
  IN_EMAIL := 'wolhacks@itcr.cr';
  IN_USERNAME := 'andres';
  IN_PASSWD := 'admin';

  sp_nuevo_administrador(
    IN_NOMBRE => IN_NOMBRE,
    IN_APELLIDO => IN_APELLIDO,
    IN_IDENTIF => IN_IDENTIF,
    IN_TIPO_IDENTIF => IN_TIPO_IDENTIF,
    IN_EMAIL => IN_EMAIL,
    IN_USERNAME => IN_USERNAME,
    IN_PASSWD => IN_PASSWD
  );
--rollback; 
END;
/