DECLARE
  IN_USUARIO VARCHAR2(200);
  IN_CATEGORIA VARCHAR2(200);
  IN_SUBCATEGORIA VARCHAR2(200);
  IN_NOMBRE_ITEM VARCHAR2(200);
  IN_DESCRIPCION VARCHAR2(200);
BEGIN
  IN_USUARIO := 'mctula';
  IN_CATEGORIA := 'Arte';
  IN_SUBCATEGORIA := 'Directo del artista';
  IN_NOMBRE_ITEM := 'Picasso xD';
  IN_DESCRIPCION := 'Pintura de Picasso buen presio :v';

  SP_NUEVO_ITEM(
    IN_USUARIO => IN_USUARIO,
    IN_CATEGORIA => IN_CATEGORIA,
    IN_SUBCATEGORIA => IN_SUBCATEGORIA,
    IN_NOMBRE_ITEM => IN_NOMBRE_ITEM,
    IN_DESCRIPCION => IN_DESCRIPCION
  );
--rollback; 
END;
/
DECLARE
  IN_USUARIO VARCHAR2(200);
  IN_CATEGORIA VARCHAR2(200);
  IN_SUBCATEGORIA VARCHAR2(200);
  IN_NOMBRE_ITEM VARCHAR2(200);
  IN_DESCRIPCION VARCHAR2(200);
BEGIN
  IN_USUARIO := 'jpfeng';
  IN_CATEGORIA := 'Arte';
  IN_SUBCATEGORIA := 'Directo del artista';
  IN_NOMBRE_ITEM := 'HERNAN JIMENEZ NFT';
  IN_DESCRIPCION := 'NFT DE ESCUBI DU';

  SP_NUEVO_ITEM(
    IN_USUARIO => IN_USUARIO,
    IN_CATEGORIA => IN_CATEGORIA,
    IN_SUBCATEGORIA => IN_SUBCATEGORIA,
    IN_NOMBRE_ITEM => IN_NOMBRE_ITEM,
    IN_DESCRIPCION => IN_DESCRIPCION
  );
--rollback; 
END;