DECLARE
  IN_NOMBRE VARCHAR2(200);
  IN_APELLIDO VARCHAR2(200);
  IN_IDENTIF VARCHAR2(200);
  IN_TIPO_IDENTIF VARCHAR2(200);
  IN_EMAIL VARCHAR2(200);
  IN_USERNAME VARCHAR2(200);
  IN_PASSWD VARCHAR2(200);
BEGIN
  IN_NOMBRE := 'Anatolio';
  IN_APELLIDO := 'Ruvalcaba Quesada';
  IN_IDENTIF := '1325123515123';
  IN_TIPO_IDENTIF := 'Cedula';
  IN_EMAIL := 'arq@ic43.com';
  IN_USERNAME := 'admin1';
  IN_PASSWD := 'admin1pw';

  sp_nuevo_administrador(
    IN_NOMBRE => IN_NOMBRE,
    IN_APELLIDO => IN_APELLIDO,
    IN_IDENTIF => IN_IDENTIF,
    IN_TIPO_IDENTIF => IN_TIPO_IDENTIF,
    IN_EMAIL => IN_EMAIL,
    IN_USERNAME => IN_USERNAME,
    IN_PASSWD => IN_PASSWD
  );
--rollback; 
END;
/
DECLARE
  IN_USERNAME NVARCHAR2(200);
  IN_NUMERO_TEL NVARCHAR2(200);
BEGIN
  IN_USERNAME := 'admin1';
  IN_NUMERO_TEL := '8346 2967 ';

  SP_EDITAR_TELEFONO(
    IN_USERNAME => IN_USERNAME,
    IN_NUMERO_TEL => IN_NUMERO_TEL
  );
--rollback; 
END;
/
DECLARE
  IN_USERNAME VARCHAR2(200);
  IN_PAIS VARCHAR2(200);
  IN_PROVINCIA VARCHAR2(200);
  IN_CANTON VARCHAR2(200);
  IN_DISTRITO VARCHAR2(200);
  OUT_INSERTED_ID NUMBER;
BEGIN
  IN_USERNAME := 'admin1';
  IN_PAIS := 'Costa Rica';
  IN_PROVINCIA := 'Cartago';
  IN_CANTON := 'La Union';
  IN_DISTRITO := 'Tres Rios';

  SP_AGREGAR_DIRECCION(
    IN_USERNAME => IN_USERNAME,
    IN_PAIS => IN_PAIS,
    IN_PROVINCIA => IN_PROVINCIA,
    IN_CANTON => IN_CANTON,
    IN_DISTRITO => IN_DISTRITO,
    OUT_INSERTED_ID => OUT_INSERTED_ID
  );
--rollback; 
END;
/